pipeline:
  test:
    image: cypress/base:6
    commands:
      - cp -a /drone/node_modules /root
      - rm -rf /drone/node_modules
      - npm install
      - npm run test-junit
      - cp -a /root/node_modules /drone
  cache:
    mount:
      - node_modules
      - .git
